---

version: '3'

services:
  openvas-master:
    build: 
      context: .
      dockerfile: Dockerfile-openvas-master.debian
    image: "${DOMAIN}/openvas-source:master-1.0"
    
  openvas-slave:
    build: 
      context: .
      dockerfile: Dockerfile-openvas-slave.debian
    image: "${DOMAIN}/openvas-source:slave-1.0"
  
