---

version: '3'

services:
  openvas-master:
    build:
      context: .
      dockerfile: Dockerfile-openvas-master.debian
    image: "${DOMAIN}/openvas-source:master-${VERSION}"

  openvas-slave:
    build:
      context: .
      dockerfile: Dockerfile-openvas-slave.debian
    image: "${DOMAIN}/openvas-source:slave-${VERSION}"

  openvas-sshvpn:
    build:
      context: .
      dockerfile: Dockerfile-openvas-sshvpn.debian
    image: "${DOMAIN}/openvas-source:sshvpn-${VERSION}"
