---

version: '3'

services:

  openvas-master:
    image: "${DOMAIN}/openvas-source:master-${STAGE}-${VERSION}"
    hostname: "openvas-master"
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "9390-9393:9390-9393"
    volumes:
      - "openvas-data:/usr/local/var/lib/openvas"
      - "gvm-data:/usr/local/var/lib/gvm"
      - "/etc/localtime:/etc/localtime:ro"
      - "${SMTP_CONFIG_PATH}:/etc/ssmtp/"

volumes:
  gvm-data:
  openvas-data:
