---

# COMPOSE DEV

version: '3'
services:

  openvas-master:
    build: 
      context: .
      dockerfile: Dockerfile-openvas-master.debian
    hostname: "openvas-master"
    restart: always
    ports:
      - "9390-9393:9390-9393"
      - "9000:443"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "openvas-dev:/usr/local/var/lib/openvas"
      - "gvm-dev:/usr/local/var/lib/gvm"
    
    
  openvas-slave:
    build: 
      context: .
      dockerfile: Dockerfile-openvas-slave.debian
    hostname: "openvas-slave"
    restart: always
    ports:
      - "19391:9390"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "openvas-dev:/usr/local/var/lib/openvas"
      - "gvm-dev:/usr/local/var/lib/gvm"
    links:
      - openvas-master
    depends_on:
      - openvas-master
      
volumes:
  gvm-dev:
  openvas-dev:
