---

version: '3'

services:
  openvas-master:
    build:
      context: .
      dockerfile: Dockerfile-openvas-master.${STAGE}
    image: "${DOMAIN}/openvas-source:master-${STAGE}-${VERSION}"

  openvas-slave:
    build:
      context: .
      dockerfile: Dockerfile-openvas-slave.${STAGE}
    image: "${DOMAIN}/openvas-source:slave-${STAGE}-${VERSION}"

  openvas-sshvpn:
    build:
      context: .
      dockerfile: Dockerfile-openvas-sshvpn.${STAGE}
    image: "${DOMAIN}/openvas-source:sshvpn-${STAGE}-${VERSION}"
