---

version: '3'

services:
  gvm-master:
    image: "${DOMAIN}/gvm-docker:master-${VERSION}-${STAGE}"
    hostname: "gvm-master"
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "9390-9393:9390-9393"
    volumes:
      - "openvas-data:/usr/local/var/lib/openvas"
      - "gvm-data:/usr/local/var/lib/gvm"
      - "/etc/localtime:/etc/localtime:ro"
      - "${SMTP_CONFIG_PATH}:/etc/ssmtp/"
    environment:
      - GVM_UPDATE_CRON=${GVM_UPDATE_CRON}

volumes:
  gvm-data:
  openvas-data:
