---

version: '3'

services:
  gvm-sshvpn:
    image: "${DOMAIN}/gvm-docker:sshvpn-${VERSION}-${STAGE}"
    hostname: "gvm-sshvpn"
    restart: always
    privileged: true
    networks:
      default:
      vpn_tunnel:
        ipv4_address: 172.66.66.67
    ports:
      - "29390:9390"
    volumes:
      - "openvas-data:/usr/local/var/lib/openvas"
      - "gvm-data:/usr/local/var/lib/gvm"
      - "/etc/localtime:/etc/localtime:ro"
      - "${SMTP_CONFIG_PATH}:/etc/ssmtp/"
      - "${SSHVPN_ROOT}/hosts/:${SSHVPN_ROOT_DOCKER}/hosts/:ro"
    links:
      - gvm-master
    depends_on:
      - gvm-master
    environment:
      - SSHVPN_ROOT_DOCKER=${SSHVPN_ROOT_DOCKER}
      - SSHVPN_INTERFACE=${SSHVPN_INTERFACE}

  sshvpn:
    image: "${DOMAIN}/sshvpn:${SSHVPN_VERSION}"
    hostname: "sshvpn"
    restart: always
    privileged: true
    networks:
      default:
      vpn_tunnel:
        ipv4_address: 172.66.66.66
    cap_add:
      - ALL
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "${SSHVPN_ROOT}:${SSHVPN_ROOT_DOCKER}"
    links:
      - gvm-master
      - gvm-sshvpn
    environment:
      - SSHVPN_ROOT_DOCKER=${SSHVPN_ROOT_DOCKER}

networks:
  vpn_tunnel:
    ipam:
      config:
        - subnet: 172.66.0.0/16

volumes:
  gvm-data:
  openvas-data:
