---

version: '3'

services:
  openvas-master:
    build:
      context: ../../dockerfile
      dockerfile: Dockerfile-openvas-master
      args:
        OS: ${OS}
        OS_VERSION: ${OS_VERSION}
        STAGE: ${STAGE}
        DATABASE: sqlite
    image: "${DOMAIN}/openvas-source:master-${VERSION}-${STAGE}"
    hostname: "openvas-master"
    restart: always
    ports:
      - "9390-9393:9390-9393"
      - "9000:443"
    volumes:
      - "openvas-dev:/usr/local/var/lib/openvas"
      - "gvm-dev:/usr/local/var/lib/gvm"
      - "/etc/localtime:/etc/localtime:ro"
      - "${SMTP_CONFIG_PATH}:/etc/ssmtp/"
    environment:
      - GREENBONE_UPDATE_CRON=${GREENBONE_UPDATE_CRON}

  openvas-slave:
    build:
      context: ../../dockerfile
      dockerfile: Dockerfile-openvas-slave
      args:
        OS: ${OS}
        OS_VERSION: ${OS_VERSION}
        STAGE: ${STAGE}
        DATABASE: sqlite
    image: "${DOMAIN}/openvas-source:slave-${VERSION}-${STAGE}"
    hostname: "openvas-slave"
    restart: always
    ports:
      - "19301:9390"
    volumes:
      - "openvas-dev:/usr/local/var/lib/openvas"
      - "gvm-dev:/usr/local/var/lib/gvm"
      - "/etc/localtime:/etc/localtime:ro"
    links:
      - openvas-master
    depends_on:
      - openvas-master
    environment:
      - ENABLE_CRON=false

  openvas-sshvpn:
    build:
      context: ../../dockerfile
      dockerfile: Dockerfile-openvas-sshvpn
      args:
        OS: ${OS}
        OS_VERSION: ${OS_VERSION}
        STAGE: ${STAGE}
        DATABASE: sqlite
    image: "${DOMAIN}/openvas-source:sshvpn-${VERSION}-${STAGE}"
    hostname: "openvas-sshvpn"
    restart: always
    privileged: true
    networks:
      default:
      vpn_tunnel:
        ipv4_address: 172.66.66.67
    ports:
      - "29301:9390"
    volumes:
      - "openvas-dev:/usr/local/var/lib/openvas"
      - "gvm-dev:/usr/local/var/lib/gvm"
      - "/etc/localtime:/etc/localtime:ro"
      - "${SSHVPN_ROOT}/hosts/:${SSHVPN_ROOT_DOCKER}/hosts/:ro"
    links:
      - openvas-master
    depends_on:
      - openvas-master
    environment:
      - SSHVPN_ROOT_DOCKER=${SSHVPN_ROOT_DOCKER}
      - SSHVPN_INTERFACE=${SSHVPN_INTERFACE}

  sshvpn:
    build:
      context: ../../extra/sshvpn
      dockerfile: Dockerfile
    hostname: "sshvpn"
    restart: always
    privileged: true
    networks:
      vpn_tunnel:
        ipv4_address: 172.66.66.66
      default:
    cap_add:
      - ALL
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "${SSHVPN_ROOT}:${SSHVPN_ROOT_DOCKER}"
    links:
      - openvas-sshvpn
    environment:
      - SSHVPN_ROOT_DOCKER=${SSHVPN_ROOT_DOCKER}

networks:
  vpn_tunnel:
    ipam:
      config:
        - subnet: 172.66.0.0/16

volumes:
  gvm-dev:
  openvas-dev:
