---

version: '3'

services:
# gvm-master
  gvm-master:
    build:
      context: ../../dockerfile
      dockerfile: Dockerfile-gvm-master
      args:
        OS: ${OS}
        OS_VERSION: ${OS_VERSION}
        STAGE: ${STAGE}
        DATABASE: postgres
    image: "${DOMAIN}/gvm-source:master-${VERSION}-postgres"
  gvm-master-stable:
    build:
      context: ../../dockerfile
      dockerfile: Dockerfile-gvm-master
      args:
        OS: ${OS}
        OS_VERSION: ${OS_VERSION}
        STAGE: ${STAGE}
        DATABASE: postgres
    image: "${DOMAIN}/gvm-source:master-${VERSION}-postgres-${STAGE}"

# gvm-slave
  gvm-slave:
    build:
      context: ../../dockerfile
      dockerfile: Dockerfile-gvm-slave
      args:
        OS: ${OS}
        OS_VERSION: ${OS_VERSION}
        STAGE: ${STAGE}
        DATABASE: postgres
    image: "${DOMAIN}/gvm-source:slave-${VERSION}-postgres"
  gvm-slave-stable:
    build:
      context: ../../dockerfile
      dockerfile: Dockerfile-gvm-slave
      args:
        OS: ${OS}
        OS_VERSION: ${OS_VERSION}
        STAGE: ${STAGE}
        DATABASE: postgres
    image: "${DOMAIN}/gvm-source:slave-${VERSION}-postgres-${STAGE}"

# gvm-slave
  gvm-sshvpn:
    build:
      context: ../../dockerfile
      dockerfile: Dockerfile-gvm-sshvpn
      args:
        OS: ${OS}
        OS_VERSION: ${OS_VERSION}
        STAGE: ${STAGE}
        DATABASE: postgres
    image: "${DOMAIN}/gvm-source:sshvpn-${VERSION}-postgres"
  gvm-sshvpn-stable:
    build:
      context: ../../dockerfile
      dockerfile: Dockerfile-gvm-sshvpn
      args:
        OS: ${OS}
        OS_VERSION: ${OS_VERSION}
        STAGE: ${STAGE}
        DATABASE: postgres
    image: "${DOMAIN}/gvm-source:sshvpn-${VERSION}-postgres-${STAGE}"
