---

version: '3'

services:
# openvas-master
  openvas-master:
    build:
      context: ../../dockerfile
      dockerfile: Dockerfile-openvas-master.stable
    image: "${DOMAIN}/openvas-source:master-${VERSION}"
  openvas-master-stable:
    build:
      context: ../../dockerfile
      dockerfile: Dockerfile-openvas-master.stable
    image: "${DOMAIN}/openvas-source:master-${VERSION}-stable"

# openvas-slave
  openvas-slave:
    build:
      context: ../../dockerfile
      dockerfile: Dockerfile-openvas-slave.stable
    image: "${DOMAIN}/openvas-source:slave-${VERSION}"
  openvas-slave-stable:
    build:
      context: ../../dockerfile
      dockerfile: Dockerfile-openvas-slave.stable
    image: "${DOMAIN}/openvas-source:slave-${VERSION}-stable"

# openvas-slave
  openvas-sshvpn:
    build:
      context: ../../dockerfile
      dockerfile: Dockerfile-openvas-sshvpn.stable
    image: "${DOMAIN}/openvas-source:sshvpn-${VERSION}"
  openvas-sshvpn-stable:
    build:
      context: ../../dockerfile
      dockerfile: Dockerfile-openvas-sshvpn.stable
    image: "${DOMAIN}/openvas-source:sshvpn-${VERSION}-stable"
