---

version: '3'

services:
# gvm-master
  gvm-master-stable:
    build:
      context: ../../dockerfile
      dockerfile: Dockerfile-gvm-master
      args:
        OS: ${OS}
        OS_VERSION: ${OS_VERSION}
        STAGE: ${STAGE}
        DATABASE: sqlite
    image: "${DOMAIN}/gvm-docker:master-${VERSION}-${STAGE}"
  gvm-master:
    build:
      context: ../../dockerfile
      dockerfile: Dockerfile-gvm-master
      args:
        OS: ${OS}
        OS_VERSION: ${OS_VERSION}
        STAGE: ${STAGE}
        DATABASE: sqlite
    image: "${DOMAIN}/gvm-docker:master-${VERSION}"
  gvm-master-latest:
    build:
      context: ../../dockerfile
      dockerfile: Dockerfile-gvm-master
      args:
        OS: ${OS}
        OS_VERSION: ${OS_VERSION}
        STAGE: ${STAGE}
        DATABASE: sqlite
    image: "${DOMAIN}/gvm-docker:master-latest"
  gvm-latest:
    build:
      context: ../../dockerfile
      dockerfile: Dockerfile-gvm-master
      args:
        OS: ${OS}
        OS_VERSION: ${OS_VERSION}
        STAGE: ${STAGE}
        DATABASE: sqlite
    image: "${DOMAIN}/gvm-docker:latest"

# gvm-slave
  gvm-slave-stable:
    build:
      context: ../../dockerfile
      dockerfile: Dockerfile-gvm-slave
      args:
        OS: ${OS}
        OS_VERSION: ${OS_VERSION}
        STAGE: ${STAGE}
        DATABASE: sqlite
    image: "${DOMAIN}/gvm-docker:slave-${VERSION}-${STAGE}"
  gvm-slave:
    build:
      context: ../../dockerfile
      dockerfile: Dockerfile-gvm-slave
      args:
        OS: ${OS}
        OS_VERSION: ${OS_VERSION}
        STAGE: ${STAGE}
        DATABASE: sqlite
    image: "${DOMAIN}/gvm-docker:slave-${VERSION}"
  gvm-slave-latest:
    build:
      context: ../../dockerfile
      dockerfile: Dockerfile-gvm-slave
      args:
        OS: ${OS}
        OS_VERSION: ${OS_VERSION}
        STAGE: ${STAGE}
        DATABASE: sqlite
    image: "${DOMAIN}/gvm-docker:slave-latest"

# gvm-slave
  gvm-sshvpn-stable:
    build:
      context: ../../dockerfile
      dockerfile: Dockerfile-gvm-sshvpn
      args:
        OS: ${OS}
        OS_VERSION: ${OS_VERSION}
        STAGE: ${STAGE}
        DATABASE: sqlite
    image: "${DOMAIN}/gvm-docker:sshvpn-${VERSION}-${STAGE}"
  gvm-sshvpn:
    build:
      context: ../../dockerfile
      dockerfile: Dockerfile-gvm-sshvpn
      args:
        OS: ${OS}
        OS_VERSION: ${OS_VERSION}
        STAGE: ${STAGE}
        DATABASE: sqlite
    image: "${DOMAIN}/gvm-docker:sshvpn-${VERSION}"
  gvm-sshvpn-latest:
    build:
      context: ../../dockerfile
      dockerfile: Dockerfile-gvm-sshvpn
      args:
        OS: ${OS}
        OS_VERSION: ${OS_VERSION}
        STAGE: ${STAGE}
        DATABASE: sqlite
    image: "${DOMAIN}/gvm-docker:sshvpn-latest"
