---

version: '3'

services:
# gvm-master
  gvm-master-stable-postgres:
    build:
      context: ../../dockerfile
      dockerfile: Dockerfile-gvm-master
      args:
        OS: ${OS}
        OS_VERSION: ${OS_VERSION}
        STAGE: ${STAGE}
        DATABASE: postgres
    image: "${DOMAIN}/gvm-docker:master-${VERSION}-postgres-${STAGE}"
  gvm-master-postgres:
    build:
      context: ../../dockerfile
      dockerfile: Dockerfile-gvm-master
      args:
        OS: ${OS}
        OS_VERSION: ${OS_VERSION}
        STAGE: ${STAGE}
        DATABASE: postgres
    image: "${DOMAIN}/gvm-docker:master-${VERSION}-postgres"
  gvm-master-latest-postgres:
    build:
      context: ../../dockerfile
      dockerfile: Dockerfile-gvm-master
      args:
        OS: ${OS}
        OS_VERSION: ${OS_VERSION}
        STAGE: ${STAGE}
        DATABASE: postgres
    image: "${DOMAIN}/gvm-docker:master-latest-postgres"
  gvm-latest-postgres:
    build:
      context: ../../dockerfile
      dockerfile: Dockerfile-gvm-master
      args:
        OS: ${OS}
        OS_VERSION: ${OS_VERSION}
        STAGE: ${STAGE}
        DATABASE: postgres
    image: "${DOMAIN}/gvm-docker:latest-postgres"

# gvm-slave
  gvm-slave-stable-postgres:
    build:
      context: ../../dockerfile
      dockerfile: Dockerfile-gvm-slave
      args:
        OS: ${OS}
        OS_VERSION: ${OS_VERSION}
        STAGE: ${STAGE}
        DATABASE: postgres
    image: "${DOMAIN}/gvm-docker:slave-${VERSION}-postgres-${STAGE}"
  gvm-slave-postgres:
    build:
      context: ../../dockerfile
      dockerfile: Dockerfile-gvm-slave
      args:
        OS: ${OS}
        OS_VERSION: ${OS_VERSION}
        STAGE: ${STAGE}
        DATABASE: postgres
    image: "${DOMAIN}/gvm-docker:slave-${VERSION}-postgres"
  gvm-slave-latest-postgres:
    build:
      context: ../../dockerfile
      dockerfile: Dockerfile-gvm-slave
      args:
        OS: ${OS}
        OS_VERSION: ${OS_VERSION}
        STAGE: ${STAGE}
        DATABASE: postgres
    image: "${DOMAIN}/gvm-docker:slave-latest-postgres"

# gvm-slave
  gvm-sshvpn-stable-postgres:
    build:
      context: ../../dockerfile
      dockerfile: Dockerfile-gvm-sshvpn
      args:
        OS: ${OS}
        OS_VERSION: ${OS_VERSION}
        STAGE: ${STAGE}
        DATABASE: postgres
    image: "${DOMAIN}/gvm-docker:sshvpn-${VERSION}-postgres-${STAGE}"
  gvm-sshvpn-postgres:
    build:
      context: ../../dockerfile
      dockerfile: Dockerfile-gvm-sshvpn
      args:
        OS: ${OS}
        OS_VERSION: ${OS_VERSION}
        STAGE: ${STAGE}
        DATABASE: postgres
    image: "${DOMAIN}/gvm-docker:sshvpn-${VERSION}-postgres"
  gvm-sshvpn-latest-postgres:
    build:
      context: ../../dockerfile
      dockerfile: Dockerfile-gvm-sshvpn
      args:
        OS: ${OS}
        OS_VERSION: ${OS_VERSION}
        STAGE: ${STAGE}
        DATABASE: postgres
    image: "${DOMAIN}/gvm-docker:sshvpn-latest-postgres"
